<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <script type="text/javascript">
        //<![CDATA[
        var BASE_URL = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";
        var BASE_URL_STORE = "<?php echo Mage::getBaseUrl(); ?>";
        //]]>
    </script>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-popup<?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>">
<div class="synchronize-block-content">
    <div class="logo-inxmail"></div>
    <h1 class="title">DATA SYNCHRONIZATION</h1>

    <div class="data-block">
        <?php echo $this->getChildHtml('content') ?>
        <span id="loader-sync"></span>
    </div>
</div>
</body>
</html>
