<?php $synchronized = $this->isSynchronized(); ?>
<script type="text/javascript">
    //<![CDATA[
    function DndInxmailSynchronizeSubscribers() {
        window.open("<?php echo $this->getCheckUrl() ?>");
        return false;
    }
    document.observe("dom:loaded", function() {
        // initially hide all containers for tab content
        $('inxmail_is_subscribed').observe('change', function(event){
            var checked = event.target.checked;
            var migrationButton = $('dndinxmail_subscriber_button');
            migrationButton.disabled = checked;
            if (checked) {
                migrationButton.addClassName('disabled');
            } else {
                migrationButton.removeClassName('disabled');
            }
        });
    });
    //]]>
</script>

<?php if ($synchronized): ?>
    <div style="margin-bottom: 5px;">
        <input type="checkbox" id="inxmail_is_subscribed" name="inxmail_is_subscribed"  checked />
        <label for="inxmail_is_subscribed"><?php echo $this->__('Prevent re-execution'); ?></label>
        <p class="note">
            <span><?php echo $this->__('Please, by migration rerun, be aware of subscribed recepients who have not yet confirmed registration or deleted from Inxmail. In this case, subscriptions / unsubscriptions are automatically transferred to Inxmail.'); ?></span>
        </p>
    </div>
<?php endif; ?>
<?php echo $this->getButtonHtml() ?>